name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: yashpc
          username: yash
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/portfolio

            git pull origin main

            /usr/bin/docker-compose down
            /usr/bin/docker-compose up -d --build --remove-orphans

            sleep 30

            /usr/bin/docker-compose --profile tools run --rm rag-index